// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: api/vc/services/verifiable.proto

package services

import (
	types2 "github.com/bhatti/GSSI/api/common/types"
	types1 "github.com/bhatti/GSSI/api/spi/types"
	types "github.com/bhatti/GSSI/api/vc/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValidateCredentialReq model
//
// This is used to validate the verifiable credential.
//
// swagger:parameters validateCredentialReq
type ValidateCredentialReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Params for validating the verifiable credential (pass the vc document as a string)
	//
	// in: body
	Credential *types.VerifiableCredential `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
}

func (x *ValidateCredentialReq) Reset() {
	*x = ValidateCredentialReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateCredentialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCredentialReq) ProtoMessage() {}

func (x *ValidateCredentialReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCredentialReq.ProtoReflect.Descriptor instead.
func (*ValidateCredentialReq) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateCredentialReq) GetCredential() *types.VerifiableCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

// SaveCredentialReq model
//
// This is used to save the verifiable credential.
//
// swagger:parameters saveCredentialReq
type SaveCredentialReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Params for saving the verifiable credential (pass the vc document as a string)
	//
	// in: body
	Credential *types.VerifiableCredential `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
}

func (x *SaveCredentialReq) Reset() {
	*x = SaveCredentialReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveCredentialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCredentialReq) ProtoMessage() {}

func (x *SaveCredentialReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCredentialReq.ProtoReflect.Descriptor instead.
func (*SaveCredentialReq) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{1}
}

func (x *SaveCredentialReq) GetCredential() *types.VerifiableCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

// SavePresentationReq model
//
// This is used to save the verifiable presentation.
//
// swagger:parameters savePresentationReq
type SavePresentationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Params for saving the verifiable presentation
	//
	// in: body
	Credential *types.VerifiablePresentation `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
}

func (x *SavePresentationReq) Reset() {
	*x = SavePresentationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SavePresentationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePresentationReq) ProtoMessage() {}

func (x *SavePresentationReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePresentationReq.ProtoReflect.Descriptor instead.
func (*SavePresentationReq) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{2}
}

func (x *SavePresentationReq) GetCredential() *types.VerifiablePresentation {
	if x != nil {
		return x.Credential
	}
	return nil
}

// GetCredentialReq model
//
// This is used to retrieve the verifiable credential.
//
// swagger:parameters getCredentialReq
type GetCredentialReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// VC ID - pass base64 version of the ID
	//
	// in: path
	// required: true
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCredentialReq) Reset() {
	*x = GetCredentialReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCredentialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialReq) ProtoMessage() {}

func (x *GetCredentialReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialReq.ProtoReflect.Descriptor instead.
func (*GetCredentialReq) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{3}
}

func (x *GetCredentialReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// CredentialRes model
//
// This is used for returning query connection result for single record search
//
// swagger:response credentialRes
type CredentialRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// in: body
	Credential *types.VerifiablePresentation `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
}

func (x *CredentialRes) Reset() {
	*x = CredentialRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialRes) ProtoMessage() {}

func (x *CredentialRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialRes.ProtoReflect.Descriptor instead.
func (*CredentialRes) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{4}
}

func (x *CredentialRes) GetCredential() *types.VerifiablePresentation {
	if x != nil {
		return x.Credential
	}
	return nil
}

// GetPresentationReq model
//
// This is used to retrieve the verifiable presentation.
//
// swagger:parameters getPresentationReq
type GetPresentationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// VP ID - pass base64 version of the ID
	// in: path
	// required: true
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPresentationReq) Reset() {
	*x = GetPresentationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPresentationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresentationReq) ProtoMessage() {}

func (x *GetPresentationReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresentationReq.ProtoReflect.Descriptor instead.
func (*GetPresentationReq) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{5}
}

func (x *GetPresentationReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetCredentialByNameReq model
//
// This is used to retrieve the verifiable credential by name.
//
// swagger:parameters getCredentialByNameReq
type GetCredentialByNameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// VC Name
	//
	// in: path
	// required: true
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetCredentialByNameReq) Reset() {
	*x = GetCredentialByNameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCredentialByNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialByNameReq) ProtoMessage() {}

func (x *GetCredentialByNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialByNameReq.ProtoReflect.Descriptor instead.
func (*GetCredentialByNameReq) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{6}
}

func (x *GetCredentialByNameReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// RemoveCredentialByNameReq model
//
// This is used to remove the verifiable credential by name.
//
// swagger:parameters removeCredentialByNameReq
type RemoveCredentialByNameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// VC Name
	//
	// in: path
	// required: true
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RemoveCredentialByNameReq) Reset() {
	*x = RemoveCredentialByNameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveCredentialByNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCredentialByNameReq) ProtoMessage() {}

func (x *RemoveCredentialByNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCredentialByNameReq.ProtoReflect.Descriptor instead.
func (*RemoveCredentialByNameReq) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveCredentialByNameReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// RemovePresentationByNameReq model
//
// This is used to remove the verifiable presentation by name.
//
// swagger:parameters removePresentationByNameReq
type RemovePresentationByNameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// VC Name
	//
	// in: path
	// required: true
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RemovePresentationByNameReq) Reset() {
	*x = RemovePresentationByNameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePresentationByNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePresentationByNameReq) ProtoMessage() {}

func (x *RemovePresentationByNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePresentationByNameReq.ProtoReflect.Descriptor instead.
func (*RemovePresentationByNameReq) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{8}
}

func (x *RemovePresentationByNameReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// CredentialRecord model
//
// This is used to return credential record.
//
// swagger:response credentialRecord
type CredentialRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// in: body
	Body *types1.Record `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *CredentialRecord) Reset() {
	*x = CredentialRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialRecord) ProtoMessage() {}

func (x *CredentialRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialRecord.ProtoReflect.Descriptor instead.
func (*CredentialRecord) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{9}
}

func (x *CredentialRecord) GetBody() *types1.Record {
	if x != nil {
		return x.Body
	}
	return nil
}

// CredentialRecordResult model
//
// This is used to return credential records.
//
// swagger:response credentialRecordResult
type CredentialRecordResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// in: body
	Result       []*types1.Record `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	TotalRecords int64            `protobuf:"varint,2,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
}

func (x *CredentialRecordResult) Reset() {
	*x = CredentialRecordResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialRecordResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialRecordResult) ProtoMessage() {}

func (x *CredentialRecordResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialRecordResult.ProtoReflect.Descriptor instead.
func (*CredentialRecordResult) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{10}
}

func (x *CredentialRecordResult) GetResult() []*types1.Record {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CredentialRecordResult) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

// presentationRecordResult model
//
// This is used to return presentation records.
//
// swagger:response presentationRecordResult
type PresentationRecordResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// in: body
	Result []*types1.Record `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *PresentationRecordResult) Reset() {
	*x = PresentationRecordResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresentationRecordResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentationRecordResult) ProtoMessage() {}

func (x *PresentationRecordResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentationRecordResult.ProtoReflect.Descriptor instead.
func (*PresentationRecordResult) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{11}
}

func (x *PresentationRecordResult) GetResult() []*types1.Record {
	if x != nil {
		return x.Result
	}
	return nil
}

// GeneratePresentationReq model
//
// This is used to generate the verifiable presentation.
//
// swagger:parameters generatePresentationReq
type GeneratePresentationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Params for generating the verifiable presentation (pass the vc document as a raw JSON)
	//
	// in: body
	Body *PresentationRequest `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *GeneratePresentationReq) Reset() {
	*x = GeneratePresentationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratePresentationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePresentationReq) ProtoMessage() {}

func (x *GeneratePresentationReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePresentationReq.ProtoReflect.Descriptor instead.
func (*GeneratePresentationReq) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{12}
}

func (x *GeneratePresentationReq) GetBody() *PresentationRequest {
	if x != nil {
		return x.Body
	}
	return nil
}

// GeneratePresentationByIDReq model
//
// This is used to generate the verifiable presentation by id.
//
// swagger:parameters generatePresentationByIDReq
type GeneratePresentationByIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Params for generating the verifiable presentation by id (pass the vc document as a raw JSON)
	//
	// in: body
	Params *PresentationRequestByID `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *GeneratePresentationByIDReq) Reset() {
	*x = GeneratePresentationByIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratePresentationByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePresentationByIDReq) ProtoMessage() {}

func (x *GeneratePresentationByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePresentationByIDReq.ProtoReflect.Descriptor instead.
func (*GeneratePresentationByIDReq) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{13}
}

func (x *GeneratePresentationByIDReq) GetParams() *PresentationRequestByID {
	if x != nil {
		return x.Params
	}
	return nil
}

// PresentationRes model
//
// This is used for returning the verifiable presentation
//
// swagger:response presentationRes
type PresentationRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// in: body
	VerifiablePresentation *types.VerifiablePresentation `protobuf:"bytes,1,opt,name=verifiablePresentation,proto3" json:"verifiablePresentation,omitempty"` // json.RawMessage
}

func (x *PresentationRes) Reset() {
	*x = PresentationRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresentationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentationRes) ProtoMessage() {}

func (x *PresentationRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentationRes.ProtoReflect.Descriptor instead.
func (*PresentationRes) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{14}
}

func (x *PresentationRes) GetVerifiablePresentation() *types.VerifiablePresentation {
	if x != nil {
		return x.VerifiablePresentation
	}
	return nil
}

// SignCredentialReq model
//
// This is used to sign a credential.
//
// swagger:parameters signCredentialReq
type SignCredentialReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Params for signing a credential
	//
	// in: body
	Params *SignCredentialRequest `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *SignCredentialReq) Reset() {
	*x = SignCredentialReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignCredentialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCredentialReq) ProtoMessage() {}

func (x *SignCredentialReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCredentialReq.ProtoReflect.Descriptor instead.
func (*SignCredentialReq) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{15}
}

func (x *SignCredentialReq) GetParams() *SignCredentialRequest {
	if x != nil {
		return x.Params
	}
	return nil
}

// SignCredentialRes model
//
// This is used for returning the sign credential response
//
// swagger:response signCredentialRes
type SignCredentialRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// in: body
	VerifiableCredential *types.VerifiableCredential `protobuf:"bytes,1,opt,name=verifiableCredential,proto3" json:"verifiableCredential,omitempty"` // json.RawMessage
}

func (x *SignCredentialRes) Reset() {
	*x = SignCredentialRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignCredentialRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCredentialRes) ProtoMessage() {}

func (x *SignCredentialRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCredentialRes.ProtoReflect.Descriptor instead.
func (*SignCredentialRes) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{16}
}

func (x *SignCredentialRes) GetVerifiableCredential() *types.VerifiableCredential {
	if x != nil {
		return x.VerifiableCredential
	}
	return nil
}

// DeriveCredentialReq model
//
// This is used for deriving a credential.
//
// swagger:parameters deriveCredentialReq
type DeriveCredentialReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Params for deriving a credential
	//
	// in: body
	Body *DeriveCredentialRequest `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *DeriveCredentialReq) Reset() {
	*x = DeriveCredentialReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeriveCredentialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeriveCredentialReq) ProtoMessage() {}

func (x *DeriveCredentialReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeriveCredentialReq.ProtoReflect.Descriptor instead.
func (*DeriveCredentialReq) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{17}
}

func (x *DeriveCredentialReq) GetBody() *DeriveCredentialRequest {
	if x != nil {
		return x.Body
	}
	return nil
}

// DeriveCredentialRes model
//
// This is used for returning the derive credential response.
//
// swagger:response deriveCredentialRes
type DeriveCredentialRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// in: body
	VerifiableCredential *types.VerifiableCredential `protobuf:"bytes,1,opt,name=verifiableCredential,proto3" json:"verifiableCredential,omitempty"` // json.RawMessage
}

func (x *DeriveCredentialRes) Reset() {
	*x = DeriveCredentialRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeriveCredentialRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeriveCredentialRes) ProtoMessage() {}

func (x *DeriveCredentialRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeriveCredentialRes.ProtoReflect.Descriptor instead.
func (*DeriveCredentialRes) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{18}
}

func (x *DeriveCredentialRes) GetVerifiableCredential() *types.VerifiableCredential {
	if x != nil {
		return x.VerifiableCredential
	}
	return nil
}

// CredentialsRequest
//
// This is used to return credential input
//
// swagger:parameters getCredentials
type GetCredentialsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *GetCredentialsReq) Reset() {
	*x = GetCredentialsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vc_services_verifiable_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCredentialsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialsReq) ProtoMessage() {}

func (x *GetCredentialsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vc_services_verifiable_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialsReq.ProtoReflect.Descriptor instead.
func (*GetCredentialsReq) Descriptor() ([]byte, []int) {
	return file_api_vc_services_verifiable_proto_rawDescGZIP(), []int{19}
}

func (x *GetCredentialsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCredentialsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_api_vc_services_verifiable_proto protoreflect.FileDescriptor

var file_api_vc_services_verifiable_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x1a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x63, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x63, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x70, 0x69, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x5b, 0x0a, 0x15, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x42, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x57,
	0x0a, 0x11, 0x53, 0x61, 0x76, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x12, 0x42, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x5b, 0x0a, 0x13, 0x53, 0x61, 0x76, 0x65, 0x50,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x44,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x22,
	0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x19, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x1b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x29, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x6c, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x2d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x22, 0x49, 0x0a, 0x18, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x2d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x53, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72, 0x65, 0x73, 0x65,
	0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x38, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65,
	0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x22, 0x5f, 0x0a, 0x1b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x12, 0x40, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x6f, 0x0a, 0x0f, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x5c, 0x0a, 0x16, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x63, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x16,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x53, 0x0a, 0x11, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x3e, 0x0a, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x6b, 0x0a, 0x11, 0x53,
	0x69, 0x67, 0x6e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x12, 0x56, 0x0a, 0x14, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x52, 0x14, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x53, 0x0a, 0x13, 0x44, 0x65, 0x72, 0x69,
	0x76, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x3c, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x44, 0x65, 0x72, 0x69, 0x76, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x6d, 0x0a,
	0x13, 0x44, 0x65, 0x72, 0x69, 0x76, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x52, 0x65, 0x73, 0x12, 0x56, 0x0a, 0x14, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x14, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x43, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x32, 0xe7, 0x0a, 0x0a, 0x14, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x5f, 0x0a, 0x12, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0e, 0x73,
	0x61, 0x76, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x22, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x53, 0x61, 0x76, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x10, 0x73, 0x61, 0x76, 0x65, 0x50, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x50,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x54, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x50, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x27,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0e, 0x73, 0x69, 0x67,
	0x6e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x22, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x1a,
	0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x60, 0x0a, 0x10, 0x64, 0x65, 0x72, 0x69, 0x76, 0x65, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x72, 0x69,
	0x76, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x1a,
	0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x44, 0x65, 0x72, 0x69, 0x76, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x50, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x17, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x00, 0x12, 0x64, 0x0a, 0x14, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72, 0x65,
	0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x18, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x79, 0x49, 0x44, 0x12, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x16, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6b,
	0x0a, 0x18, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x68, 0x61, 0x74, 0x74, 0x69,
	0x2f, 0x47, 0x53, 0x53, 0x49, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x63, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_vc_services_verifiable_proto_rawDescOnce sync.Once
	file_api_vc_services_verifiable_proto_rawDescData = file_api_vc_services_verifiable_proto_rawDesc
)

func file_api_vc_services_verifiable_proto_rawDescGZIP() []byte {
	file_api_vc_services_verifiable_proto_rawDescOnce.Do(func() {
		file_api_vc_services_verifiable_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_vc_services_verifiable_proto_rawDescData)
	})
	return file_api_vc_services_verifiable_proto_rawDescData
}

var file_api_vc_services_verifiable_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_vc_services_verifiable_proto_goTypes = []interface{}{
	(*ValidateCredentialReq)(nil),        // 0: api.vc.services.ValidateCredentialReq
	(*SaveCredentialReq)(nil),            // 1: api.vc.services.SaveCredentialReq
	(*SavePresentationReq)(nil),          // 2: api.vc.services.SavePresentationReq
	(*GetCredentialReq)(nil),             // 3: api.vc.services.GetCredentialReq
	(*CredentialRes)(nil),                // 4: api.vc.services.CredentialRes
	(*GetPresentationReq)(nil),           // 5: api.vc.services.GetPresentationReq
	(*GetCredentialByNameReq)(nil),       // 6: api.vc.services.GetCredentialByNameReq
	(*RemoveCredentialByNameReq)(nil),    // 7: api.vc.services.RemoveCredentialByNameReq
	(*RemovePresentationByNameReq)(nil),  // 8: api.vc.services.RemovePresentationByNameReq
	(*CredentialRecord)(nil),             // 9: api.vc.services.CredentialRecord
	(*CredentialRecordResult)(nil),       // 10: api.vc.services.CredentialRecordResult
	(*PresentationRecordResult)(nil),     // 11: api.vc.services.PresentationRecordResult
	(*GeneratePresentationReq)(nil),      // 12: api.vc.services.GeneratePresentationReq
	(*GeneratePresentationByIDReq)(nil),  // 13: api.vc.services.GeneratePresentationByIDReq
	(*PresentationRes)(nil),              // 14: api.vc.services.PresentationRes
	(*SignCredentialReq)(nil),            // 15: api.vc.services.SignCredentialReq
	(*SignCredentialRes)(nil),            // 16: api.vc.services.SignCredentialRes
	(*DeriveCredentialReq)(nil),          // 17: api.vc.services.DeriveCredentialReq
	(*DeriveCredentialRes)(nil),          // 18: api.vc.services.DeriveCredentialRes
	(*GetCredentialsReq)(nil),            // 19: api.vc.services.GetCredentialsReq
	(*types.VerifiableCredential)(nil),   // 20: api.vc.types.VerifiableCredential
	(*types.VerifiablePresentation)(nil), // 21: api.vc.types.VerifiablePresentation
	(*types1.Record)(nil),                // 22: api.spi.types.Record
	(*PresentationRequest)(nil),          // 23: api.vc.services.PresentationRequest
	(*PresentationRequestByID)(nil),      // 24: api.vc.services.PresentationRequestByID
	(*SignCredentialRequest)(nil),        // 25: api.vc.services.SignCredentialRequest
	(*DeriveCredentialRequest)(nil),      // 26: api.vc.services.DeriveCredentialRequest
	(*types2.Empty)(nil),                 // 27: api.common.types.Empty
	(*types2.EmptyResponse)(nil),         // 28: api.common.types.EmptyResponse
}
var file_api_vc_services_verifiable_proto_depIdxs = []int32{
	20, // 0: api.vc.services.ValidateCredentialReq.credential:type_name -> api.vc.types.VerifiableCredential
	20, // 1: api.vc.services.SaveCredentialReq.credential:type_name -> api.vc.types.VerifiableCredential
	21, // 2: api.vc.services.SavePresentationReq.credential:type_name -> api.vc.types.VerifiablePresentation
	21, // 3: api.vc.services.CredentialRes.credential:type_name -> api.vc.types.VerifiablePresentation
	22, // 4: api.vc.services.CredentialRecord.body:type_name -> api.spi.types.Record
	22, // 5: api.vc.services.CredentialRecordResult.result:type_name -> api.spi.types.Record
	22, // 6: api.vc.services.PresentationRecordResult.result:type_name -> api.spi.types.Record
	23, // 7: api.vc.services.GeneratePresentationReq.body:type_name -> api.vc.services.PresentationRequest
	24, // 8: api.vc.services.GeneratePresentationByIDReq.params:type_name -> api.vc.services.PresentationRequestByID
	21, // 9: api.vc.services.PresentationRes.verifiablePresentation:type_name -> api.vc.types.VerifiablePresentation
	25, // 10: api.vc.services.SignCredentialReq.params:type_name -> api.vc.services.SignCredentialRequest
	20, // 11: api.vc.services.SignCredentialRes.verifiableCredential:type_name -> api.vc.types.VerifiableCredential
	26, // 12: api.vc.services.DeriveCredentialReq.body:type_name -> api.vc.services.DeriveCredentialRequest
	20, // 13: api.vc.services.DeriveCredentialRes.verifiableCredential:type_name -> api.vc.types.VerifiableCredential
	0,  // 14: api.vc.services.VerifiableController.validateCredential:input_type -> api.vc.services.ValidateCredentialReq
	1,  // 15: api.vc.services.VerifiableController.saveCredential:input_type -> api.vc.services.SaveCredentialReq
	2,  // 16: api.vc.services.VerifiableController.savePresentation:input_type -> api.vc.services.SavePresentationReq
	3,  // 17: api.vc.services.VerifiableController.getCredential:input_type -> api.vc.services.GetCredentialReq
	5,  // 18: api.vc.services.VerifiableController.getPresentation:input_type -> api.vc.services.GetPresentationReq
	6,  // 19: api.vc.services.VerifiableController.getCredentialByName:input_type -> api.vc.services.GetCredentialByNameReq
	19, // 20: api.vc.services.VerifiableController.getCredentials:input_type -> api.vc.services.GetCredentialsReq
	15, // 21: api.vc.services.VerifiableController.signCredential:input_type -> api.vc.services.SignCredentialReq
	17, // 22: api.vc.services.VerifiableController.deriveCredential:input_type -> api.vc.services.DeriveCredentialReq
	27, // 23: api.vc.services.VerifiableController.getPresentations:input_type -> api.common.types.Empty
	12, // 24: api.vc.services.VerifiableController.generatePresentation:input_type -> api.vc.services.GeneratePresentationReq
	13, // 25: api.vc.services.VerifiableController.generatePresentationByID:input_type -> api.vc.services.GeneratePresentationByIDReq
	7,  // 26: api.vc.services.VerifiableController.removeCredentialByName:input_type -> api.vc.services.RemoveCredentialByNameReq
	8,  // 27: api.vc.services.VerifiableController.removePresentationByName:input_type -> api.vc.services.RemovePresentationByNameReq
	28, // 28: api.vc.services.VerifiableController.validateCredential:output_type -> api.common.types.EmptyResponse
	28, // 29: api.vc.services.VerifiableController.saveCredential:output_type -> api.common.types.EmptyResponse
	28, // 30: api.vc.services.VerifiableController.savePresentation:output_type -> api.common.types.EmptyResponse
	4,  // 31: api.vc.services.VerifiableController.getCredential:output_type -> api.vc.services.CredentialRes
	14, // 32: api.vc.services.VerifiableController.getPresentation:output_type -> api.vc.services.PresentationRes
	9,  // 33: api.vc.services.VerifiableController.getCredentialByName:output_type -> api.vc.services.CredentialRecord
	10, // 34: api.vc.services.VerifiableController.getCredentials:output_type -> api.vc.services.CredentialRecordResult
	16, // 35: api.vc.services.VerifiableController.signCredential:output_type -> api.vc.services.SignCredentialRes
	18, // 36: api.vc.services.VerifiableController.deriveCredential:output_type -> api.vc.services.DeriveCredentialRes
	11, // 37: api.vc.services.VerifiableController.getPresentations:output_type -> api.vc.services.PresentationRecordResult
	14, // 38: api.vc.services.VerifiableController.generatePresentation:output_type -> api.vc.services.PresentationRes
	14, // 39: api.vc.services.VerifiableController.generatePresentationByID:output_type -> api.vc.services.PresentationRes
	28, // 40: api.vc.services.VerifiableController.removeCredentialByName:output_type -> api.common.types.EmptyResponse
	28, // 41: api.vc.services.VerifiableController.removePresentationByName:output_type -> api.common.types.EmptyResponse
	28, // [28:42] is the sub-list for method output_type
	14, // [14:28] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_vc_services_verifiable_proto_init() }
func file_api_vc_services_verifiable_proto_init() {
	if File_api_vc_services_verifiable_proto != nil {
		return
	}
	file_api_vc_services_presentation_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_vc_services_verifiable_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateCredentialReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveCredentialReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SavePresentationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCredentialReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPresentationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCredentialByNameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveCredentialByNameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePresentationByNameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialRecordResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresentationRecordResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneratePresentationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneratePresentationByIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresentationRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignCredentialReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignCredentialRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeriveCredentialReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeriveCredentialRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vc_services_verifiable_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCredentialsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_vc_services_verifiable_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_vc_services_verifiable_proto_goTypes,
		DependencyIndexes: file_api_vc_services_verifiable_proto_depIdxs,
		MessageInfos:      file_api_vc_services_verifiable_proto_msgTypes,
	}.Build()
	File_api_vc_services_verifiable_proto = out.File
	file_api_vc_services_verifiable_proto_rawDesc = nil
	file_api_vc_services_verifiable_proto_goTypes = nil
	file_api_vc_services_verifiable_proto_depIdxs = nil
}
