// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: api/ld/services/ld.proto

package services

import (
	types "github.com/bhatti/GSSI/api/ld/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddContextsRequest is a request model for adding JSON-LD contexts.
// swagger:parameters addContextsReq
type AddContextsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// in: body
	Documents []*types.Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
}

func (x *AddContextsRequest) Reset() {
	*x = AddContextsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ld_services_ld_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddContextsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContextsRequest) ProtoMessage() {}

func (x *AddContextsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ld_services_ld_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContextsRequest.ProtoReflect.Descriptor instead.
func (*AddContextsRequest) Descriptor() ([]byte, []int) {
	return file_api_ld_services_ld_proto_rawDescGZIP(), []int{0}
}

func (x *AddContextsRequest) GetDocuments() []*types.Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

type AddContextsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddContextsResponse) Reset() {
	*x = AddContextsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ld_services_ld_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddContextsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContextsResponse) ProtoMessage() {}

func (x *AddContextsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ld_services_ld_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContextsResponse.ProtoReflect.Descriptor instead.
func (*AddContextsResponse) Descriptor() ([]byte, []int) {
	return file_api_ld_services_ld_proto_rawDescGZIP(), []int{1}
}

// RefreshRemoteProviderRequest model for updating JSON-LD contexts from the remote context provider.
//
// swagger:parameters refreshRemoteProviderReq
type RefreshRemoteProviderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// in: path
	// required: true
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RefreshRemoteProviderRequest) Reset() {
	*x = RefreshRemoteProviderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ld_services_ld_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshRemoteProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRemoteProviderRequest) ProtoMessage() {}

func (x *RefreshRemoteProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ld_services_ld_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRemoteProviderRequest.ProtoReflect.Descriptor instead.
func (*RefreshRemoteProviderRequest) Descriptor() ([]byte, []int) {
	return file_api_ld_services_ld_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshRemoteProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RefreshRemoteProviderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshRemoteProviderResponse) Reset() {
	*x = RefreshRemoteProviderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ld_services_ld_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshRemoteProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRemoteProviderResponse) ProtoMessage() {}

func (x *RefreshRemoteProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ld_services_ld_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRemoteProviderResponse.ProtoReflect.Descriptor instead.
func (*RefreshRemoteProviderResponse) Descriptor() ([]byte, []int) {
	return file_api_ld_services_ld_proto_rawDescGZIP(), []int{3}
}

// DeleteRemoteProviderRequest model for deleting remote provider and JSON-LD contexts from that provider.
//
// swagger:parameters deleteRemoteProviderReq
type DeleteRemoteProviderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// in: path
	// required: true
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteRemoteProviderRequest) Reset() {
	*x = DeleteRemoteProviderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ld_services_ld_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRemoteProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRemoteProviderRequest) ProtoMessage() {}

func (x *DeleteRemoteProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ld_services_ld_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRemoteProviderRequest.ProtoReflect.Descriptor instead.
func (*DeleteRemoteProviderRequest) Descriptor() ([]byte, []int) {
	return file_api_ld_services_ld_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRemoteProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRemoteProviderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteRemoteProviderResponse) Reset() {
	*x = DeleteRemoteProviderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ld_services_ld_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRemoteProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRemoteProviderResponse) ProtoMessage() {}

func (x *DeleteRemoteProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ld_services_ld_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRemoteProviderResponse.ProtoReflect.Descriptor instead.
func (*DeleteRemoteProviderResponse) Descriptor() ([]byte, []int) {
	return file_api_ld_services_ld_proto_rawDescGZIP(), []int{5}
}

// AddRemoteProviderRequest is a request model for adding a new remote context provider.
type AddRemoteProviderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
}

func (x *AddRemoteProviderRequest) Reset() {
	*x = AddRemoteProviderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ld_services_ld_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRemoteProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRemoteProviderRequest) ProtoMessage() {}

func (x *AddRemoteProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ld_services_ld_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRemoteProviderRequest.ProtoReflect.Descriptor instead.
func (*AddRemoteProviderRequest) Descriptor() ([]byte, []int) {
	return file_api_ld_services_ld_proto_rawDescGZIP(), []int{6}
}

func (x *AddRemoteProviderRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type AddRemoteProviderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddRemoteProviderResponse) Reset() {
	*x = AddRemoteProviderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ld_services_ld_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRemoteProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRemoteProviderResponse) ProtoMessage() {}

func (x *AddRemoteProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ld_services_ld_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRemoteProviderResponse.ProtoReflect.Descriptor instead.
func (*AddRemoteProviderResponse) Descriptor() ([]byte, []int) {
	return file_api_ld_services_ld_proto_rawDescGZIP(), []int{7}
}

// swagger:parameters addRemoteProviderReq
type DocAddRemoteProviderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// in: body
	Body *AddRemoteProviderRequest `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *DocAddRemoteProviderRequest) Reset() {
	*x = DocAddRemoteProviderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ld_services_ld_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocAddRemoteProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocAddRemoteProviderRequest) ProtoMessage() {}

func (x *DocAddRemoteProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ld_services_ld_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocAddRemoteProviderRequest.ProtoReflect.Descriptor instead.
func (*DocAddRemoteProviderRequest) Descriptor() ([]byte, []int) {
	return file_api_ld_services_ld_proto_rawDescGZIP(), []int{8}
}

func (x *DocAddRemoteProviderRequest) GetBody() *AddRemoteProviderRequest {
	if x != nil {
		return x.Body
	}
	return nil
}

// GetAllRemoteProvidersRequest model is an empty model
//
// swagger:parameters getAllRemoteProvidersReq
type GetAllRemoteProvidersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *GetAllRemoteProvidersRequest) Reset() {
	*x = GetAllRemoteProvidersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ld_services_ld_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRemoteProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRemoteProvidersRequest) ProtoMessage() {}

func (x *GetAllRemoteProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ld_services_ld_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRemoteProvidersRequest.ProtoReflect.Descriptor instead.
func (*GetAllRemoteProvidersRequest) Descriptor() ([]byte, []int) {
	return file_api_ld_services_ld_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllRemoteProvidersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllRemoteProvidersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetAllRemoteProvidersResponse model for getting list of all remote context providers from the underlying storage.
type GetAllRemoteProvidersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Providers []*types.RemoteProviderRecord `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
}

func (x *GetAllRemoteProvidersResponse) Reset() {
	*x = GetAllRemoteProvidersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ld_services_ld_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRemoteProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRemoteProvidersResponse) ProtoMessage() {}

func (x *GetAllRemoteProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ld_services_ld_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRemoteProvidersResponse.ProtoReflect.Descriptor instead.
func (*GetAllRemoteProvidersResponse) Descriptor() ([]byte, []int) {
	return file_api_ld_services_ld_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllRemoteProvidersResponse) GetProviders() []*types.RemoteProviderRecord {
	if x != nil {
		return x.Providers
	}
	return nil
}

// swagger:response getAllRemoteProvidersResp
type DocGetAllRemoteProvidersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// in: body
	Body *GetAllRemoteProvidersResponse `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *DocGetAllRemoteProvidersResponse) Reset() {
	*x = DocGetAllRemoteProvidersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ld_services_ld_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocGetAllRemoteProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocGetAllRemoteProvidersResponse) ProtoMessage() {}

func (x *DocGetAllRemoteProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ld_services_ld_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocGetAllRemoteProvidersResponse.ProtoReflect.Descriptor instead.
func (*DocGetAllRemoteProvidersResponse) Descriptor() ([]byte, []int) {
	return file_api_ld_services_ld_proto_rawDescGZIP(), []int{11}
}

func (x *DocGetAllRemoteProvidersResponse) GetBody() *GetAllRemoteProvidersResponse {
	if x != nil {
		return x.Body
	}
	return nil
}

// RefreshAllRemoteProvidersRequest model is an empty model
//
// swagger:parameters refreshAllRemoteProvidersReq
type RefreshAllRemoteProvidersRequst struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshAllRemoteProvidersRequst) Reset() {
	*x = RefreshAllRemoteProvidersRequst{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ld_services_ld_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshAllRemoteProvidersRequst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAllRemoteProvidersRequst) ProtoMessage() {}

func (x *RefreshAllRemoteProvidersRequst) ProtoReflect() protoreflect.Message {
	mi := &file_api_ld_services_ld_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAllRemoteProvidersRequst.ProtoReflect.Descriptor instead.
func (*RefreshAllRemoteProvidersRequst) Descriptor() ([]byte, []int) {
	return file_api_ld_services_ld_proto_rawDescGZIP(), []int{12}
}

type RefreshAllRemoteProvidersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshAllRemoteProvidersResponse) Reset() {
	*x = RefreshAllRemoteProvidersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ld_services_ld_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshAllRemoteProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAllRemoteProvidersResponse) ProtoMessage() {}

func (x *RefreshAllRemoteProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ld_services_ld_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAllRemoteProvidersResponse.ProtoReflect.Descriptor instead.
func (*RefreshAllRemoteProvidersResponse) Descriptor() ([]byte, []int) {
	return file_api_ld_services_ld_proto_rawDescGZIP(), []int{13}
}

var File_api_ld_services_ld_proto protoreflect.FileDescriptor

var file_api_ld_services_ld_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x64, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2f, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x70, 0x69, 0x2e,
	0x6c, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x15, 0x61, 0x70, 0x69,
	0x2f, 0x6c, 0x64, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6c, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x15,
	0x0a, 0x13, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e, 0x0a, 0x1c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x1d, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x36, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x1b, 0x0a,
	0x19, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5c, 0x0a, 0x1b, 0x64, 0x6f,
	0x63, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x64,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x4e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x61, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6c, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x22, 0x66, 0x0a, 0x20, 0x64,
	0x6f, 0x63, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x42, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6c, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x22, 0x21, 0x0a, 0x1f, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x73, 0x74, 0x22, 0x23, 0x0a, 0x21, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd1, 0x05, 0x0a, 0x14,
	0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x12, 0x5a, 0x0a, 0x0b, 0x61, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x73, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x64, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c,
	0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x6c, 0x0a, 0x11, 0x61, 0x64, 0x64, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x64, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x78,
	0x0a, 0x15, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x64,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x64, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x75, 0x0a, 0x14, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x12, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x78, 0x0a, 0x15, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x12, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c,
	0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x64,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x83, 0x01, 0x0a, 0x19, 0x72, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x12, 0x30, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x64,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6c, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x68,
	0x61, 0x74, 0x74, 0x69, 0x2f, 0x47, 0x53, 0x53, 0x49, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x64,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_ld_services_ld_proto_rawDescOnce sync.Once
	file_api_ld_services_ld_proto_rawDescData = file_api_ld_services_ld_proto_rawDesc
)

func file_api_ld_services_ld_proto_rawDescGZIP() []byte {
	file_api_ld_services_ld_proto_rawDescOnce.Do(func() {
		file_api_ld_services_ld_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ld_services_ld_proto_rawDescData)
	})
	return file_api_ld_services_ld_proto_rawDescData
}

var file_api_ld_services_ld_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_ld_services_ld_proto_goTypes = []interface{}{
	(*AddContextsRequest)(nil),                // 0: api.ld.services.AddContextsRequest
	(*AddContextsResponse)(nil),               // 1: api.ld.services.AddContextsResponse
	(*RefreshRemoteProviderRequest)(nil),      // 2: api.ld.services.RefreshRemoteProviderRequest
	(*RefreshRemoteProviderResponse)(nil),     // 3: api.ld.services.RefreshRemoteProviderResponse
	(*DeleteRemoteProviderRequest)(nil),       // 4: api.ld.services.DeleteRemoteProviderRequest
	(*DeleteRemoteProviderResponse)(nil),      // 5: api.ld.services.DeleteRemoteProviderResponse
	(*AddRemoteProviderRequest)(nil),          // 6: api.ld.services.AddRemoteProviderRequest
	(*AddRemoteProviderResponse)(nil),         // 7: api.ld.services.AddRemoteProviderResponse
	(*DocAddRemoteProviderRequest)(nil),       // 8: api.ld.services.docAddRemoteProviderRequest
	(*GetAllRemoteProvidersRequest)(nil),      // 9: api.ld.services.GetAllRemoteProvidersRequest
	(*GetAllRemoteProvidersResponse)(nil),     // 10: api.ld.services.GetAllRemoteProvidersResponse
	(*DocGetAllRemoteProvidersResponse)(nil),  // 11: api.ld.services.docGetAllRemoteProvidersResponse
	(*RefreshAllRemoteProvidersRequst)(nil),   // 12: api.ld.services.RefreshAllRemoteProvidersRequst
	(*RefreshAllRemoteProvidersResponse)(nil), // 13: api.ld.services.RefreshAllRemoteProvidersResponse
	(*types.Document)(nil),                    // 14: api.ld.types.Document
	(*types.RemoteProviderRecord)(nil),        // 15: api.ld.types.RemoteProviderRecord
}
var file_api_ld_services_ld_proto_depIdxs = []int32{
	14, // 0: api.ld.services.AddContextsRequest.documents:type_name -> api.ld.types.Document
	6,  // 1: api.ld.services.docAddRemoteProviderRequest.body:type_name -> api.ld.services.AddRemoteProviderRequest
	15, // 2: api.ld.services.GetAllRemoteProvidersResponse.providers:type_name -> api.ld.types.RemoteProviderRecord
	10, // 3: api.ld.services.docGetAllRemoteProvidersResponse.body:type_name -> api.ld.services.GetAllRemoteProvidersResponse
	0,  // 4: api.ld.services.LinkedDataController.addContexts:input_type -> api.ld.services.AddContextsRequest
	6,  // 5: api.ld.services.LinkedDataController.addRemoteProvider:input_type -> api.ld.services.AddRemoteProviderRequest
	2,  // 6: api.ld.services.LinkedDataController.refreshRemoteProvider:input_type -> api.ld.services.RefreshRemoteProviderRequest
	4,  // 7: api.ld.services.LinkedDataController.deleteRemoteProvider:input_type -> api.ld.services.DeleteRemoteProviderRequest
	9,  // 8: api.ld.services.LinkedDataController.getAllRemoteProviders:input_type -> api.ld.services.GetAllRemoteProvidersRequest
	12, // 9: api.ld.services.LinkedDataController.refreshAllRemoteProviders:input_type -> api.ld.services.RefreshAllRemoteProvidersRequst
	1,  // 10: api.ld.services.LinkedDataController.addContexts:output_type -> api.ld.services.AddContextsResponse
	7,  // 11: api.ld.services.LinkedDataController.addRemoteProvider:output_type -> api.ld.services.AddRemoteProviderResponse
	3,  // 12: api.ld.services.LinkedDataController.refreshRemoteProvider:output_type -> api.ld.services.RefreshRemoteProviderResponse
	5,  // 13: api.ld.services.LinkedDataController.deleteRemoteProvider:output_type -> api.ld.services.DeleteRemoteProviderResponse
	10, // 14: api.ld.services.LinkedDataController.getAllRemoteProviders:output_type -> api.ld.services.GetAllRemoteProvidersResponse
	13, // 15: api.ld.services.LinkedDataController.refreshAllRemoteProviders:output_type -> api.ld.services.RefreshAllRemoteProvidersResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_ld_services_ld_proto_init() }
func file_api_ld_services_ld_proto_init() {
	if File_api_ld_services_ld_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ld_services_ld_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddContextsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ld_services_ld_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddContextsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ld_services_ld_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshRemoteProviderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ld_services_ld_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshRemoteProviderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ld_services_ld_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRemoteProviderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ld_services_ld_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRemoteProviderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ld_services_ld_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRemoteProviderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ld_services_ld_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRemoteProviderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ld_services_ld_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocAddRemoteProviderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ld_services_ld_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRemoteProvidersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ld_services_ld_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRemoteProvidersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ld_services_ld_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocGetAllRemoteProvidersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ld_services_ld_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshAllRemoteProvidersRequst); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ld_services_ld_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshAllRemoteProvidersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ld_services_ld_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ld_services_ld_proto_goTypes,
		DependencyIndexes: file_api_ld_services_ld_proto_depIdxs,
		MessageInfos:      file_api_ld_services_ld_proto_msgTypes,
	}.Build()
	File_api_ld_services_ld_proto = out.File
	file_api_ld_services_ld_proto_rawDesc = nil
	file_api_ld_services_ld_proto_goTypes = nil
	file_api_ld_services_ld_proto_depIdxs = nil
}
